name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  MONGO_URI: mongodb://localhost:27017
  MONGO_DB: notifications

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        env:
          QUARKUS_MONGODB_CONNECTION_STRING: mongodb://localhost:27017
          QUARKUS_MONGODB_DATABASE: notifications
      active-mq:
        image: quay.io/artemiscloud/activemq-artemis-broker:1.0.25
        ports:
          - 61616:61616
          - 5672:5672
          - 8161:8161
        env:
          QUARKUS_ARTEMIS_USERNAME: quarkus
          QUARKUS_ARTEMIS_PASSWORD: quarkus

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with Maven
        run: mvn -B package --file pom.xml

      - name: Docker login
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        run: docker build -t jernejofic444/notification-service -f src/main/docker/Dockerfile.jvm .


      - name: Push Docker image
        run: docker push jernejofic444/notification-service